### ISSUE TITLE
Is IPTV safe for me?

### ISSUE THREAD

**Issue by Kingem39p** [Pirate-Crew/IPTV-Sharp#1]
Salve, questo è il primo Issue, e sono proprio io.

mi è sorta una domanda.. magari usandolo proprio da Windows, col proprio computer, siete sicuri che non possano trovare l'ip?

grazie.

**Comment by ludo237** [comment]
Onestamente non ha senso quello che hai appena detto. E' normale che il tuo IP sia visibile ma se tu che ti devi preoccupare di questo onestamente :warning:
