### ISSUE TITLE
informazione 

### ISSUE THREAD

**Issue by Tonyrock90** [Pirate-Crew/IPTV-Sharp#7]
Non ho capito come si usa la versione sharp 1.1, ho estratto i file e li ho inseriti nella cartella contenente quelli di sharp 1.0, ma non cambia nulla.

**Comment by Delfioh** [comment]
Su questo repo non c'è ancora la release compilata aggiornata, per adesso scarica da qui
[https://github.com/Delfioh/IPTV-Sharp/releases](url)
