### ISSUE TITLE
segnalazione

### ISSUE THREAD

**Issue by Tonyrock90** [Pirate-Crew/IPTV-Sharp#8]
volevo segnalare che il programma smette di funzionare quando si selezionano alcuni server presenti nella lista. I funzionanti si contano sulle dita di una mano. Inoltre nella cartella output rilascia oltre ad account funzionanti anche centinaia di account inesistenti di 1kb. Credo proprio che siano i tentativi non andati a buon fine. Grazie

**Comment by Delfioh** [comment]
La release qui presente non è aggiornata, scarica da qui per ora:
[https://github.com/Delfioh/IPTV-Sharp/releases](url)

Ci tengo comunque a precisare che non diamo supporto all'utilizzo in quanto il programma è chiaramente specificato come "uso dimostrativo"

**Comment by Tonyrock90** [comment]
Il link non va, si lo so, era solamente per testarlo.
